finder_arm:
  # Publish all joint states -------------------------
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  # Position controllers -----------------------------
  base_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_rotation
    pid: {
      p: 1.0,
      i: 1.0,
      d: 0.0
    }

  shoulder_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_rotation
    pid: {
      p: 1.0,
      i: 1.0,
      d: 0.0
    }

  elbow_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_rotation
    pid: {
      p: 1.0,
      i: 1.0,
      d: 0.0
    }

  roll_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: roll_rotation
    pid: {
      p: 1.0,
      i: 1.0,
      d: 0.0
    }

  pitch_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: pitch_rotation
    pid: {
      p: 1.0,
      i: 1.0,
      d: 0.0
    }

  roll_rotation_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: roll_rotation_2
    pid: {
      p: 1.0,
      i: 1.0,
      d: 0.0
    }

  gripper_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_rotation
    pid: {
      p: 1.0,
      i: 1.0,
      d: 0.0
    }